### ISSUE TITLE
Companion errors out if it's not the first/only remote connection to Voicemeeter

### ISSUE THREAD

**Issue by KLyvers** [bitfocus/companion-module-vbaudio-voicemeeter#14]
**Describe the bug**
When using another app (BarRaider streamdeck native plugin) to also remote control Voicemeeter, the companion connection errors out.

**To Reproduce**
Setup and configure native streamdeck Voicemeeter plugin by BarRaider
Once it is connected to the first remote "slot"
Build connection in Companion, it will not connect

**Expected behaviour**
Both CAN co-exist, but only if the companion makes the hook/connection first.

**Screenshots**

**System (please complete the following information):**

- Companion Version: [3.1.2 (3.1.2+6243-stable-05c37a10)](https://bitfocus.io/companion/)
- Voicemeeter: Banana 2.0.6.8

**Additional context**

**Comment by thedist** [comment]
First off, try a newer version of Companion and see if the issue persists. If it does, I'm not sure there's much that can be done due to the way the library hooks to the dll.

Plus, there's never been any guarantee of interoperability between Companion and other Stream Deck software which is why in production most people use just Companion as the risk of a conflict when live is too great.

**Comment by KLyvers** [comment]
Upgraded to the beta version and the issue persists. While I can appreciate that using the native Streamdeck app and companion at the same time is not great, there is not feature parity between the two control methods.

**Comment by KLyvers** [comment]
I will send a request, but it feels like short/long press actions might be not in scope for Companion.

Meanwhile I resolved this issue by delaying the loading of the companion app after login.

**Comment by istnv** [comment]
> I will send a request, but it feels like short/long press actions might be not in scope for Companion.
> 
These have been in companion for a long time.
